### ISSUE TITLE
Would be good to serialise or export entities to table

### ISSUE THREAD

**Issue by togfoxy** [Keyslam/Concord#62]
When I want to build a "save game" function I need to hardcode components and component properties into a table and then serialise the table with bitser. Then reverse the process when loading the game.

Would be good if I can serialise an entity and then dump straight to file so I can have some persistence around the Concord entities.

**Comment by flamendless** [comment]
There's entity serialize method that will serialize it along with the components, component class alo have serialize/deserialize methods that you can override

**Comment by togfoxy** [comment]
@flamendless How to invoke? Not documented?

**Comment by pablomayobre** [comment]
Same thing but add a "de" in front

**Comment by flamendless** [comment]
> @flamendless How to invoke? Not documented?
> 
> Looked in the code: function Entity:serialize() function Component:serialize()
> 
> Okay - now how to deserialise?

i think it's only available in the `experimental` branch

**Comment by pablomayobre** [comment]
It has been there for ages

https://github.com/Keyslam/Concord/blob/7a4bfaf33c6fdcb572e943529b1a77980944906e/concord/world.lua#L319-L350
