### ISSUE TITLE
how sorting entities world?

### ISSUE THREAD

**Issue by pankiwi** [Keyslam/Concord#64]
i try make easy z by Y position
but i can't sort entities

**Comment by wolfboyft** [comment]
This might do what you want, if not, flip the `>`
```lua
local sprites = {}
for i, v in ipairs(self.sprites) do
	sprites[i] = v -- Copy pool to table to be sorted
end
table.sort(sprites, function(a, b)
	return a.position.y > b.position.y
end)
for _, e in ipairs(sprites) do
	self:drawSprite(e)
end
```

**Comment by pablomayobre** [comment]
Pools can be sorted if you are running on dev or experimental

```lua
self.sprites:sort(function(a, b)
	return a.position.y > b.position.y
end)

for _, entity in ipairs(self.sprites) do
	--Use your sorted entity here
end
```

**Comment by pablomayobre** [comment]
Closing this, but feel free to reopen if you need more help, also there is a [Discord](https://discord.gg/DjhxaFv) which is a good place to get quick answers on questions like this one
